export let tabs = [
    {
        'title': 'Vision',
        'description': 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste facilis neque suscipit, molestias quo est quasi modi. Aspernatur incidunt quam eligendi veritatis voluptatem fugit fuga tempore possimus, porro ex! Facilis incidunt sit placeat quos delectus possimus distinctio debitis, eaque ratione, suscipit facere eveniet et at.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste facilis neque suscipit, molestias quo est quasi modi. Aspernatur incidunt quam eligendi veritatis voluptatem fugit fuga tempore possimus, porro ex! Facilis incidunt sit placeat quos delectus possimus distinctio debitis, eaque ratione, suscipit facere eveniet et at.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste facilis neque suscipit, molestias quo est quasi modi. Aspernatur incidunt quam eligendi veritatis voluptatem fugit fuga tempore possimus, porro ex! Facilis incidunt sit placeat quos delectus possimus distinctio debitis, eaque ratione, suscipit facere eveniet et at.'
    },
    {
        'title': 'Mission',
        'description': '22Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste facilis neque suscipit, molestias quo est quasi modi. Aspernatur incidunt quam eligendi veritatis voluptatem fugit fuga tempore possimus, porro ex! Facilis incidunt sit placeat quos delectus possimus distinctio debitis, eaque ratione, suscipit facere eveniet et at.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste facilis neque suscipit, molestias quo est quasi modi. Aspernatur incidunt quam eligendi veritatis voluptatem fugit fuga tempore possimus, porro ex! Facilis incidunt sit placeat quos delectus possimus distinctio debitis, eaque ratione, suscipit facere eveniet et at.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste facilis neque suscipit, molestias quo est quasi modi. Aspernatur incidunt quam eligendi veritatis voluptatem fugit fuga tempore possimus, porro ex! Facilis incidunt sit placeat quos delectus possimus distinctio debitis, eaque ratione, suscipit facere eveniet et at.'
    }, {
        'title': 'Value',
        'description': '33Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste facilis neque suscipit, molestias quo est quasi modi. Aspernatur incidunt quam eligendi veritatis voluptatem fugit fuga tempore possimus, porro ex! Facilis incidunt sit placeat quos delectus possimus distinctio debitis, eaque ratione, suscipit facere eveniet et at.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste facilis neque suscipit, molestias quo est quasi modi. Aspernatur incidunt quam eligendi veritatis voluptatem fugit fuga tempore possimus, porro ex! Facilis incidunt sit placeat quos delectus possimus distinctio debitis, eaque ratione, suscipit facere eveniet et at.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste facilis neque suscipit, molestias quo est quasi modi. Aspernatur incidunt quam eligendi veritatis voluptatem fugit fuga tempore possimus, porro ex! Facilis incidunt sit placeat quos delectus possimus distinctio debitis, eaque ratione, suscipit facere eveniet et at.'
    }
]